# Generated by Django 4.1.4 on 2022-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('TamilNadu', 'TamilNadu'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra')], max_length=30)),
            ],
        ),
    ]
